service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-qq9zitez5n
  name: backend-service-1-qq9zitez5n
  selector: backend-service-1-qq9zitez5n
  type:
  - ClusterIP
  - NodePort
namespace: wewerwer-dev
pvc:
  name: pvc-backend-service-1-qq9zitez5n
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-qq9zitez5n
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: backend-service-1-qq9zitez5n
    tag: "7993-4609-backend-service-1-qq9zitez5n-66c43b5"
    secret: regsecret
  container:
    name: backend-service-1-qq9zitez5n
    port: 8080
  volume:
    name: pvc-backend-service-1-qq9zitez5n
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    mysql:
      name: secret-mysql-service-1-ikqkblvk8i
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-qq9zitez5n
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
